Edits to files-part 2
pyansys/dev-guide pull request #161
Opened 2022-08-10 18:18 UTC by PipKat

Edits to ensure that all doc and coding style content removed from the Ansys Sphinx Template documentation and the PyAEDT documentation exists somewhere in the PyAnsys Developer's Guide.

2022-08-10 19:51 UTC, PipKat commented
I can see how specifying a reference designator is better than using the title. I'm sure there there is a better way to catch problems than letting the Documentation check identify them one by one, but I'm not sure what that way is.

2022-08-11 05:47 UTC, RobPasMue approved these changes
LGTM! Only some minor comments. Thanks @PipKat

2022-08-11 05:47 UTC, RobPasMue commented on doc/source/how-to/testing.rst
>  ----------------------------
```suggestion
Test using GitHub Actions
-------------------------
```

2022-08-11 05:47 UTC, RobPasMue commented on doc/source/how-to/testing.rst
>  ~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
Configure code coverage
~~~~~~~~~~~~~~~~~~~~~~~
```

2022-08-11 05:47 UTC, RobPasMue commented on doc/source/how-to/testing.rst
>  ---------------------
```suggestion
Test code coverage
------------------
```

2022-08-11 05:47 UTC, RobPasMue commented on doc/source/how-to/releasing.rst
>  ~~~~~~~~~~~~~~~~~~~~
```suggestion
Publish to GitHub
~~~~~~~~~~~~~~~~~
```

2022-08-11 05:47 UTC, RobPasMue commented on doc/source/how-to/releasing.rst
> +-------------
```suggestion
Branch model
------------
```

2022-08-11 05:47 UTC, RobPasMue commented on doc/source/how-to/contributing.rst
>  -----------------------
```suggestion
Create a pull request
---------------------
```

2022-08-11 05:47 UTC, RobPasMue commented on doc/source/how-to/contributing.rst
>  -------------------------
```suggestion
Create a GitHub account
-----------------------
```

2022-08-11 06:17 UTC, jorgepiloto requested changes
Hi @PipKat,
thanks for addressing this. @RobPasMue spotted most of the required changes before merging this, thank you Roberto. I just added a couple of suggestions.

Glad to see our docs improve every day! 🚀

2022-08-11 06:17 UTC, jorgepiloto commented on doc/source/doc-style/index.rst
> +documentation, see :ref:`Documenting` in the How-to section.
Maybe, we could also link the `How-to` section by doing:

```suggestion
documentation, see :ref:`Documenting` in the :ref`How-to` section.
```

2022-08-11 06:17 UTC, jorgepiloto commented on doc/source/how-to/releasing.rst
> +information, see :ref: `Automate release process`.
```suggestion
information, see :ref:`Automate release process`.
```

2022-08-11 07:57 UTC, MaxJPRey commented on README.rst
> +It also provides how-to information and summarizes packing, coding, and
```suggestion
It also provides how-to information and summarizes packaging, coding, and
```

2022-08-11 07:59 UTC, MaxJPRey commented on README.rst
> +From the **About** area for the repository, you can click the for the latest web-based
```suggestion
From the **About** area for the repository, you can click for the latest web-based
```

2022-08-11 08:25 UTC, MaxJPRey commented on doc/source/how-to/releasing.rst
>  auto-generated gRPC' interface files from a feature or service that is still
```suggestion
auto-generated gRPC interface files from a feature or service that is still
```

2022-08-11 08:29 UTC, MaxJPRey approved these changes

2022-08-11 13:45 UTC, RobPasMue commented on doc/source/how-to/releasing.rst
> +information, see :ref:`Automate release process`.
```suggestion
information, see :ref:`Automate the release process`.
```

Title changed name =)

2022-08-11 14:09 UTC, jorgepiloto approved these changes

2022-08-11 14:14 UTC, merged