Show the documentation structure
pyansys/dev-guide pull request #248
Opened 2023-01-30 18:32 UTC by akaszynski

Show the documentation structure in `structure.rst`.

2023-01-30 19:19 UTC, akaszynski commented
@jorgepiloto, if you agree, please add `AUTHORS.md` to https://github.com/ansys/ansys-templates/

2023-01-30 19:29 UTC, phxnsharp commented
I'm still philosophically working though this one in my head. At Ansys we create products and libraries that are much bigger than individual contributors. Projects should always be done from the perspective that new people will be taking them over, and probably relatively quickly. This encourages sustainable documentation. An author list can be a crutch for not writing proper documentation.

For example, ansys-common-variableinterop was written by a 5 person team and might during any sprint be worked on by another team of similar size. An author list would be long from the start, and unwieldy quickly.  Besides, GitHub already keeps track of who contributes for us.

2023-01-31 05:53 UTC, jorgepiloto requested changes

2023-01-31 05:53 UTC, jorgepiloto commented on .pre-commit-config.yaml
> +  rev: 5.11.5
```suggestion
  rev: 5.12.0
```

2023-01-31 05:53 UTC, jorgepiloto commented on doc/source/packaging/structure.rst
> +.. literalinclude:: code/changelog_file.md
```suggestion
.. literalinclude:: code/authors_file.md
```

2023-01-31 06:19 UTC, jorgepiloto commented
Thanks for enhancing this, @akaszynski.

Your answer got me thinking, @phxnsharp and I decided to open [this disucussion](https://github.com/pyansys/dev-guide/discussions/250) so we can agree about the usage and content of the `AUTHORS` file. The discussion presents some exmaples from the GNU project and Google.

2023-01-31 06:19 UTC, jorgepiloto approved these changes

2023-01-31 06:20 UTC, merged